# Generated by Django 2.1.1 on 2018-11-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
